### ISSUE TITLE
Form Rows do not  keep the continuity of their side edges in snapshot

### ISSUE THREAD

**Issue by Velin92** [BarredEwe/Prefire#27]
## How to reproduce

Just make a very simple form view like this:
```
static var previews: some View {
        Form {
            Section("Test") {
                Text("Row 1")
                Text("Row 2")
            }
        }
    }
```

The preview that SwiftUI Canvas shows is the following:
<img width="472" alt="Screenshot 2023-09-22 at 11 04 41" src="https://github.com/BarredEwe/Prefire/assets/34335419/50c3face-4c00-485e-9302-472f195efd23">

The generated previews instead is:
![test_compoundIcon Test](https://github.com/BarredEwe/Prefire/assets/34335419/5b18fa2c-cc50-4bcd-969c-589f7c3253c6)

Is very subtle but if you check the edges on the sides of the two rows you will see that the rounding happens PER ROW in the preview snapshot, instead of happening only at the end and at the start of the row like in the SwiftUI preview.

These happens for all views that use the system rows.
<img width="472" alt="Screenshot 2023-09-22 at 11 04 41" src="https://github.com/BarredEwe/Prefire/assets/34335419/ac69e696-537d-476b-a110-e99feee719fb">

![test_compoundIcon Test](https://github.com/BarredEwe/Prefire/assets/34335419/e769b380-bcc2-4846-addc-0b858eb67233)

**Comment by BarredEwe** [comment]
Hi! **Prefire** uses the library - [swift snapshot testing](https://github.com/pointfreeco/swift-snapshot-testing) inside. I tried to reproduce using this library and the bug is also reproduced.

As I understand it, the problem is that the library uses `SwiftUI.View` wraps in a `UIHostingViewController`. I will try to look for an alternative or a workaround to this problem. In the meantime, I recommend bringing this problem to the library [repository](https://github.com/pointfreeco/swift-snapshot-testing).
